from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/$', views.detail, name='detail'),
    url(r'^detail/(?P<goodname>.+)/$', views.detail, name='detail'),
    url(r'^detail1/(?P<goodname>.+)/(?P<page>\d+)/$', views.detail, name='detail1'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login_phone/$', views.login_phone, name='login_phone'),
    url(r'^car/$', views.car, name='car'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register_phone/$', views.register_phone, name='register_phone'),
    url(r'^register_email/$', views.register_email, name='register_email'),
    url(r'^generate_yzm/$', views.generate_yzm, name='generate_yzm'),
    url(r'^order/$', views.order, name='order'),
    url(r'^find_password/$', views.find_password, name='find_password'),
    url(r'^find_pw_sendmsg/$', views.find_pw_sendmsg, name='find_pw_sendmsg'),
    url(r'^find_generate_yzm/$', views.find_generate_yzm, name='find_generate_yzm'),
    url(r'^setnewpassword/$', views.setnewpassword, name='setnewpassword'),
    url(r'^register_yzm/$', views.register_yzm, name='register_yzm'),
    url(r'^sendmail/$', views.sendMail, name='sendmail'),
    url(r'^gotocar/$', views.gotocar, name='gotocar'),
    # url(r'^delect/$', views.delect, name='delect'),
    url(r'^delect/(\d+)$', views.delect, name='delect'),
    url(r'^buy_now/$', views.buy_now, name='buy_now'),
    url(r'^buynum_add/$', views.buynum_add, name='buynum_add'),
    url(r'^dingdan/$', views.dingdan, name='dingdan'),
    url(r'^confirm_buy/$', views.confirm_buy, name='confirm_buy'),
    url(r'^pay/$', views.ali_buy, name='ali_buy'),
    url(r'^user/$', views.user0, name='user'),
    url(r'^user/msg/$', views.user_msg, name='user_msg'),
    url(r'^user/msg/(?P<msgid>\d+)/$', views.user_msg_detail, name='user_msg_detail'),
    url(r'^user/order/$', views.user_order, name='user_order'),
    url(r'^user/returns/$', views.user_returns, name='user_returns'),
    url(r'^user/drawback/$', views.user_drawback, name='user_drawback'),
    url(r'^user/comment/$', views.user_comment, name='user_comment'),
    url(r'^user/points/$', views.user_points, name='user_points'),
    url(r'^user/coupon/$', views.user_coupon, name='user_coupon'),
    url(r'^user/vip/$', views.user_vip, name='user_vip'),
    url(r'^user/addr/$', views.receive_addr, name='receive_addr'),
    url(r'^user/safety/$', views.user_safety, name='user_safety'),
    url(r'^user/arrival/$', views.goods_arrival, name='goods_arrival'),
    url(r'^user/goodstype/(?P<tid>\d+)/$', views.goods_type, name='goods_type'),
    url(r'^user/userinfo/$', views.user_info, name='user_info'),

]
