"""
Django settings for Shopping project.

Generated by 'django-admin startproject' using Django 1.11.16.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4=f+rfh!d8n3&hpffbfdor-gcwar=6_8=q+5udeb^^o1&@h(tb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# DEBUG = False
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'App.apps.AppConfig',
    'rest_framework',
    'Admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Shopping.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Shopping.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hw_db',
        'HOST':'49.234.170.69',
        'USER':'ooo',
        'PASSWORD':'123456',
        'PORT':3306
        # 'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'hw_db',
        # 'HOST':'127.0.0.1',
        # 'USER':'root',
        # 'PASSWORD':'123456',
        # 'PORT':3306
    # 'ENGINE': 'django.db.backends.mysql',
    # 'NAME': 'day03',
    # 'HOST':'127.0.0.1',
    # 'USER':'root',
    # 'PASSWORD':'123456',
    # 'PORT':3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
# 配置公共的static静态文件的路径
STATIC_ROOT = os.path.join(BASE_DIR,'collectstatic')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# 设置session的过期时间
MAXAGE = 3 * 24 * 3600

# 阿里云短信验证码配置
SMS_CONFIG = {
    'ACCESS_KEY_ID':'LTAIDHOYSjYcvyVt',
    'ACCESS_KEY_SECRET':'qrEgykmXX4e6GUMFOqzuiLZ5gsUxSC',
    'SignName':"成少雷",
    'TemplateCode':"SMS_102315005"
}

# 发送邮件配置
EMAIL_HOST = 'smtp.126.com'
# EMAIL_PORT = 25
EMAIL_HOST_USER = 'landmark_csl@126.com'
EMAIL_HOST_PASSWORD = 'land123'
EMAIL_FROM = 'python<landmark_csl@126.com>'

# 分页配置
# 每页记录个数
COUNTOFPAGE = 2
#每页的页码范围
PAGERANGE = 6

# 确保您的秘钥文件符合标准
APP_PRIVATE_KEY = open(os.path.join(BASE_DIR,'app_private_key.pem')).read()
ALIPAY_PUBLIC_KEY = open(os.path.join(BASE_DIR, 'alipay_public_key.pem')).read()
ALI_APP_ID = "2016101300678293"

# 设置上传文文件路路径
MDEIA_ROOT = os.path.join(BASE_DIR,'static/upload')

# 分页配置
# 每页记录个数
COUNTOFPAGE = 5
# 每页的页码范围
PAGERANGE = 10
